# Generated by Django 5.0.7 on 2024-08-03 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('can_renew_book', 'Renew book'), ('can_view_borrowed', 'View borrowed books'))},
        ),
    ]
