# Generated by Django 5.0.7 on 2024-08-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_book_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='languages',
            field=models.ManyToManyField(help_text='Select a Language for this book', to='catalog.language'),
        ),
    ]
